"""Initial migration

Revision ID: 31a7e43918f4
Revises: 
Create Date: 2025-12-29 12:17:31.931914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a7e43918f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_table('episodeos')
    op.drop_table('series')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('series_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('actores', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('evaluacion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('poster', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sinopsis', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_de_temporadas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("genero::text = ANY (ARRAY['ACCION'::character varying, 'ROMANCE'::character varying, 'COMEDIA'::character varying, 'DRAMA'::character varying, 'CRIMEN'::character varying]::text[])", name='series_genero_check'),
    sa.PrimaryKeyConstraint('id', name='series_pkey'),
    sa.UniqueConstraint('titulo', name='uk_sujdgbuv4embh3cjvu1sux7ri'),
    postgresql_ignore_search_path=False
    )
    op.create_table('episodeos',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('evaluacion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_lanzamiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero_episodeo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temporada', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('serie_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], name='fkeljy48ggbrdoy8wyrla75p650'),
    sa.PrimaryKeyConstraint('id', name='episodeos_pkey')
    )
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
